"""One-off demo data seed for the dashboard (NOT a locked file; NEVER the
locked table). Writes a single DuckDB file that:

  1. Holds this repo's own SENSOR readings for the DEVELOPMENT seed table
     (901-906) - generated by src/generator.py and ingested through this
     repo's own src/ingest.py, both unmodified, both imported not edited.
  2. Holds the cleared plant demo's own STATE/COUNT/ALARM/HEARTBEAT tables
     for its one deterministic synthetic day, ingested through the pinned
     plant demo's OWN ingester.Ingester (vendor/plant-shift-oee-report,
     unmodified) - called directly with each event's JSON payload
     (Ingester.handle_raw), the same message-shape simulate.py would
     publish over MQTT, without needing a broker for this demo.
  3. Holds one pass of monitoring's rule + model alert log over the
     freshly ingested sensor readings.

The Streamlit app (dashboard/app.py) only ever READS the resulting file;
this script is the only thing that writes to it.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from dashboard import REPO_ROOT  # noqa: F401  (import first: wires sys.path)

import duckdb

import features as feat
import generator
import ingest
from twin_config import load_config

from monitoring.alert_log import run_monitoring

DEV_SEEDS = {901, 902, 903, 904, 905, 906}


# One representative asset-window per machine, from whichever dev split
# carries it (LABELLER only exists in "test"). This is a LIVE-VIEW demo,
# not the frozen evaluation, so it deliberately ingests only the last
# `window_hours` of one split per asset rather than the full multi-day dev
# dataset (that full ingest is exercised, unbounded, in tests/test_ingest.py
# and tests/test_runner_pipeline.py; a dashboard demo does not need to
# replay days of 1Hz history through the row-at-a-time validated ingest).
_DEMO_STRATA = (("validation", "FILLER"), ("validation", "CAPPER"), ("test", "LABELLER"))


def seed_sensor_data(con, cfg: dict, window_hours: float = 3.0) -> dict:
    ds = generator.generate("dev", cfg=cfg)
    seeds = {s for sp in ds.splits.values() for s in sp.seeds}
    assert seeds == DEV_SEEDS, "the dashboard demo seed must only ever use development seeds"
    ing = ingest.SensorIngester(con=con, cfg=cfg)
    window_s = int(window_hours * 3600)
    per_stratum = {}
    windows = {}   # "split/asset" -> (tag, start, stop): exactly what was ingested
    for split, asset in _DEMO_STRATA:
        readings = ds.readings[(split, asset)]
        tag = cfg["line"]["assets"][asset]["tag"]
        stop = readings.t0 + readings.n
        start = max(readings.t0, stop - window_s)
        msgs = generator.to_messages(readings, tag, start=start, stop=stop, cfg=cfg)
        for m in msgs:
            ing.handle_raw(m)
        key = f"{split}/{asset}"
        per_stratum[key] = len(msgs)
        windows[key] = (tag, start, stop)
    ing.commit()
    return {"messages_by_stratum": per_stratum, "reconciliation": ing.reconciliation(),
           "dataset_hash": generator.dataset_hash(ds), "window_hours": window_hours,
           "windows": windows}


def seed_plant_oee_data(con) -> dict:
    """Ingests the cleared plant demo's own deterministic day through its
    own Ingester, unmodified - no MQTT broker needed for a one-shot demo
    seed (Ingester.handle_raw() takes one message at a time)."""
    from events import ordered_events
    from ingester import Ingester

    ingv = Ingester(con=con)
    for e in ordered_events():
        e = dict(e)
        ts = e.pop("ts")
        ingv.handle_raw(json.dumps({**e, "ts": ts.isoformat()}))
    ingv.commit()
    return dict(ingv.stats)


def seed_monitoring_alerts(con, cfg: dict, windows: dict, *, model_warmup_windows: int = 180) -> dict:
    """Scores exactly the bounded window ingested for each stratum (never
    the frozen protocol's full split) as its own self-contained span for
    features.compute_features - a live monitor over recent history, not a
    locked-evaluation split."""
    out = {}
    for key, (tag, start, stop) in windows.items():
        readings = ingest.readings_grid(con, tag, start, stop, cfg)
        frame = feat.compute_features(readings, start, stop, split_name=key, cfg=cfg)
        out[key] = run_monitoring(con, tag, frame, cfg, model_warmup_windows=model_warmup_windows)
    return out


def seed(db_path: Path, *, force: bool = False, cfg: dict | None = None,
        window_hours: float = 3.0, model_warmup_windows: int = 600) -> dict:
    db_path.parent.mkdir(parents=True, exist_ok=True)
    if force and db_path.exists():
        db_path.unlink()
    cfg = cfg or load_config()
    con = duckdb.connect(str(db_path))
    try:
        sensor_summary = seed_sensor_data(con, cfg, window_hours=window_hours)
        oee_summary = seed_plant_oee_data(con)
        monitoring_summary = seed_monitoring_alerts(con, cfg, sensor_summary.pop("windows"),
                                                    model_warmup_windows=model_warmup_windows)
    finally:
        con.close()
    return {"db": str(db_path), "sensor": sensor_summary, "plant_oee": oee_summary,
           "monitoring": monitoring_summary}


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--db", default="out/twin_demo.duckdb")
    p.add_argument("--force", action="store_true", help="delete an existing DB file first")
    p.add_argument("--window-hours", type=float, default=3.0,
                   help="hours of each demo asset's most recent history to ingest")
    p.add_argument("--model-warmup-windows", type=int, default=600,
                   help="eligible windows used to fit the operational IsolationForest baseline")
    args = p.parse_args()
    summary = seed(Path(args.db), force=args.force, window_hours=args.window_hours,
                   model_warmup_windows=args.model_warmup_windows)
    print(json.dumps(summary, indent=1, default=str))


if __name__ == "__main__":
    main()
